name: my_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^5.1.0
  cupertino_icons: ^1.0.2
  go_router: ^12.0.0
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  firebase_core: ^2.1.1  # Needed for Crashlytics below
  firebase_crashlytics: ^3.3.5  # Error reporting
  games_services: ^3.0.0  # Achievements and leaderboards
  in_app_purchase: ^3.0.1  # In-app purchases
  confetti: ^0.7.0
  fade_out_particle: ^1.2.1
  text_to_path_maker: ^0.6.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.my_flutter
    iosBundleIdentifier: com.example.myFlutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
